language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - pip install --upgrade pip
  - pip install wheel
  - pip install pytest
  - pip install requests
  - pip instaall validators
# command to run tests

script:
  - python tests.py
